# Generated by Django 2.1.1 on 2018-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.IntegerField()),
                ('TID', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('plain', models.TextField()),
                ('url', models.TextField()),
                ('sourceLink', models.TextField()),
                ('sourceText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
