# Generated by Django 2.1.1 on 2018-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.IntegerField()),
                ('relation', models.TextField()),
            ],
        ),
    ]
